version: '3.3'
services:
  api:
    image: node:14-alpine
    volumes:
      - ./services/api:/app
    working_dir: /app    
    environment: 
      MONGO_AUTH_DB: admin
      MONGO_URI: mongodb://mongo/myproject
      MONGO_USER: root
      MONGO_PASSWORD: root
    ports:
      - 127.0.0.1:3000:3000
    depends_on: 
      - mongo
    command: tail -f /dev/null

  mongo:    
    image: mongo:4.2-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

    volumes:
        - ./services/mongo:/data/db